### ISSUE TITLE
Bulk insert using sql web

### ISSUE THREAD

**Issue by pooja-chhabriya** [ujjwalguptaofficial/sqljs#10]
Can I insert multiple records at once.

**Comment by ujjwalguptaofficial** [comment]
@pooja-chhabriya take a look at doc - https://github.com/ujjwalguptaofficial/sqlweb/wiki/Insert#insert-multiple-records-at-once

**Comment by pooja-chhabriya** [comment]
Thanks it is working now. Can you please tell me how to upsert using SQL
web like we have in js store.
