### ISSUE TITLE
cannot select specific columns

### ISSUE THREAD

**Issue by mburahmeh** [ujjwalguptaofficial/sqljs#3]
i faced this issue

"{message: "column createdon exist in both table msdyn_workordertype & ntwapp_translation", type: "invalid_join_query"}"

the column existed on both tables so what can i do if i cannot select specific columns ?

**Comment by ujjwalguptaofficial** [comment]
Hi 

You can use "as" for aliasing a column name just like sql. Here is an example - 

```
select Customers.CustomerName as name, Customers.ContactName as cName, Customers.CustomerID as cId from Orders join Customers 
on 
Orders.CustomerID=Customers.CustomerID
```

**Comment by mburahmeh** [comment]
@ujjwalguptaofficial aliasing is working fine but the returned query still contains all columns plus the alias column , what i need is how to select **aliasing columns only** without other columns

**Comment by mburahmeh** [comment]
> Hi
> 
> You can use "as" for aliasing a column name just like sql. Here is an example -
> 
> ```
> select Customers.CustomerName as name, Customers.ContactName as cName, Customers.CustomerID as cId from Orders join Customers 
> on 
> Orders.CustomerID=Customers.CustomerID
> ```

aliasing is working fine but the returned query still contains all columns plus the alias column , what i need is how to select aliasing columns only without other columns

**Comment by mburahmeh** [comment]
Hello,

 i added 2 issues to the sqlweb on github, so please take a look.

https://github.com/ujjwalguptaofficial/sqlweb/issues
