### ISSUE TITLE
connection.addPlugin is not a function

### ISSUE THREAD

**Issue by carper7** [ujjwalguptaofficial/sqljs#33]
I am testing one of the examples in jsstore and I am receiving the following error: formList.html:21 Uncaught TypeError: connection.addPlugin is not a function. I am testing it on a tablet. Everywhere I check for this error I can't find anything related. It would be nice to see real examples setting this up for using the jsstore. I want to have the sqlweb functionality in place to use sql on indexexDB stores. What am I missing? See code below taken from the wiki page at https://github.com/ujjwalguptaofficial/sqlweb/wiki.

**Comment by ujjwalguptaofficial** [comment]
you are doing right but you are using older version of jsstore. Please update it to latest version or let me know your current version.

**Comment by carper7** [comment]
Hi, so where do I get the recent version? could you please point me out to the right links where to get this?

Thank You.

**Comment by carper7** [comment]
Never mind. I found the latest version and I got it working so far.  You have done a marvelous job by developing this wrapper. Thank you so much for such a wonderful job; you have made my life and so many others so easy. With this, you took a huge load from developer's backs; now we can forget about the old deprecated websql.

Thanks again.

**Comment by ujjwalguptaofficial** [comment]
@carper7 thanks so much for nice words :). Please spread the word about jsstore, sqlweb.
