### ISSUE TITLE
AND clause will not allow for boolean

### ISSUE THREAD

**Issue by gimzani** [ujjwalguptaofficial/sqljs#34]
First - this is an awesome project - thanks for making it.

I have a table called Customers where there is a boolean flag for IsActive.

When I say:
  SELECT FROM Customers WHERE Type='new' && IsActive=true

I get:
  Expected One or more whitespaces or column value but "t" found.

Any idea what might be happening?

**Comment by ujjwalguptaofficial** [comment]
Thanks for the compliment @gimzani :heart: 

@gimzani true & false value is not allowed because indexedb doesn't add indexing on boolean type. Have a look at this thread - https://github.com/ujjwalguptaofficial/JsStore/issues/11
