### ISSUE TITLE
Throws error when searching for empty string

### ISSUE THREAD

**Issue by kwlayman** [ujjwalguptaofficial/sqljs#38]
I am using the latest versions of JsStore and SqlWeb.

To get around the can't search for null problem I put empty strings in those columns but when I try to select for them I get this: Expected One or more whitespaces or column value but \"'\" found."

If I put a value in the quotes it works.

select * from table where middle_name = ''

How do I search for an empty string?

**Comment by ujjwalguptaofficial** [comment]
will fix this

**Comment by ujjwalguptaofficial** [comment]
issue has been fixed in v 1.6.2
