### ISSUE TITLE
Is "return" option of INSERT clause working 

### ISSUE THREAD

**Issue by brilliapps** [ujjwalguptaofficial/sqljs#41]
Hello,
sqlweb is a nice plugin
Couple of weeks ago i had issue with getting return id of an inserted row. As far as i remember i used js from:
https://github.com/ujjwalguptaofficial/sqlweb/tree/master/examples/simple%20example/scripts
and add.js (i use pure js, no additional stuff like composer, etc.)

There is an example from the wiki where return keyword is to return rowId
INSERT INTO CUSTOMERS ("{ID:1,NAME:'Ramesh',AGE:32,ADDRESS:'Ahmedabad',SALARY:2000} return");
Is this "return" working, do i have an old version of the sqlweb from the aforementioned link? How is it supposed to work, can i link an "id" named column with the returned value?
The mentioned add.js use this for insert: 
`
 var query = new connection.$sql.Query("insert into Student values ({Name:'@name',Gender:'@gender',Country:'@country',City:'@city'})")
 `
There is no "return" keyword there, if it were it would indicate to me that i was using it wrong. So i have no clue what should i do about the last inserted id.

And also there was issue with a syntax (i saw it using console.log) that the sqlweb didn't accept return keyword. It treated it as an error.

I also saw some differencies (just two maybe) between syntaxes in the wiki f.e.
https://github.com/ujjwalguptaofficial/sqlweb/wiki
there we have:
CREATE TABLE
CREATE DB
but here with the name in url Create-Database
https://github.com/ujjwalguptaofficial/sqlweb/wiki/Create-Database
we have what really works:
DEFINE dbname
DEFINE tablename
And it's fine, just it took some time to figure it out :) .

Also how do i create table name or database if it not exists, like in sqlite, quouting it from memory it would be:
CREATE TABLE IF NOT EXISTS

Thank you in advance for any information. Any update on documentation would also help others.

**Comment by ujjwalguptaofficial** [comment]
> Also how do i create table name or database if it not exists, like in sqlite, quouting it from memory it would be:
CREATE TABLE IF NOT EXISTS

this is not possible as sqlweb uses indexeddb. and inside indexedb you can not just add or update column without some planing. Have a look at - https://jsstore.net/tutorial/update-schema/

**Comment by brilliapps** [comment]
Ok, thank you for your reply and information.
