### ISSUE TITLE
Module parse failed: Unexpected token (356:25)

### ISSUE THREAD

**Issue by marwanzak** [ujjwalguptaofficial/sqljs#6]
I have error when I try to use it in my Vuejs project.
`import * as SqlWeb from 'sqlweb';`
ERROR in ./node_modules/sqlweb/dist/sqlweb.commonjs2.js
Module parse failed: Unexpected token (356:25)
You may need an appropriate loader to handle this file type.
|           var columns = {};
|           all.forEach(function(column){
|               columns = {...columns,...column}
|           });
|           var versionData = ver==null?null:ver['version'];

**Comment by ujjwalguptaofficial** [comment]
Hi

Check out the code used in this example - https://github.com/ujjwalguptaofficial/sqlweb/blob/master/examples/webpack/src/service/idb_service.js

**Comment by marwanzak** [comment]
Hi,

I used the code in the example. But, when I try to import SqlWeb the message appears

**Comment by ujjwalguptaofficial** [comment]
As the error says - you need appropriate loader means webpack cant find the loader to parse the code.
